In [1]:
import numpy as np

x= np.array([1,2,3,4,"dfd"])
print(x)
print( type(x))

['1' '2' '3' '4' 'dfd']
<class 'numpy.ndarray'>


In [2]:
y= [1,2,3,4,5]
print(y)
print( type(y))

[1, 2, 3, 4, 5]
<class 'list'>


## Array

In [3]:
import numpy as np

In [4]:
x= [1,2,3,4,5,6]

y= np.array(x)
print(y)

[1 2 3 4 5 6]


In [5]:
a=[]

for i in range(1,5):
    b= int(input("enter number:"))
    a.append(b)

print(np.array(a))


enter number: 11
enter number: 12
enter number: 13
enter number: 14


[11 12 13 14]


## 2D Array

In [6]:
ar2= np.array([[1,2,3],[4,5,6]])
print(ar2)

[[1 2 3]
 [4 5 6]]


In [7]:
print(ar2.ndim)

2


## 3D array

In [8]:
ar3= np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(ar3)
print("Dimension of this array is ",ar3.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Dimension of this array is  3


## Zeros 

In [9]:
zero= np.zeros((3,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Ones

In [10]:
one =np.ones((3,3))
print(one)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Fill array with any numbers 

In [11]:
one =np.full((3,3), 4)
print(one)

[[4 4 4]
 [4 4 4]
 [4 4 4]]


# NumPy Array Slicing

## 1D array

In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print()

print(arr[3])
print()

print(arr)          

[2 3 4 5]

4

[1 2 3 4 5 6 7]


## 2D array

In [14]:
import numpy as np
arr= np.array([[1, 2, 3, 4, 5],
               [6, 7, 8, 9, 10]])

print(arr)
print()

print("dimensions:", arr.ndim)
print()

print("attributes of (1,4) is:", arr[1,4])
print()

print("slice of the array:")
print(arr[: , :3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

dimensions: 2

attributes of (1,4) is: 10

slice of the array:
[[1 2 3]
 [6 7 8]]


## 3D Array 

In [15]:
arr= np.array([[[1,2,3,4,5], 
                [6,7,8,9,10]]])

print(arr)
print(arr.shape)

print(arr[0, 0, 3])
print()

print(arr[0, : , 2:])
print()


print(arr[0, : , 1:4])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]]
(1, 2, 5)
4

[[ 3  4  5]
 [ 8  9 10]]

[[2 3 4]
 [7 8 9]]


# NumPy Array Copy vs View

In [16]:
arr= np.array([1, 2, 3, 4, 5])

x= arr.copy()
print(x)
print("base of x is :",x.base)

print()
y= arr.view()
print(y)

print()

print("base of y :")
print(y.base)

[1 2 3 4 5]
base of x is : None

[1 2 3 4 5]

base of y :
[1 2 3 4 5]


# Shape of an Array

In [17]:
arr= np.array([1,2,3,4,5])
print(arr.shape)
print(arr.ndim)

(5,)
1


In [18]:
arr= np.array([[1,2,3,4],
               [5,6,7,8]])
print(arr.shape)
print(arr.ndim)

(2, 4)
2


In [19]:
arr= np.array([[[1,2,3],
                [5,6,7],
                [8,9,10]]])
print(arr.shape)
print(arr.ndim)

(1, 3, 3)
3


In [20]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [21]:
## Reshaping arrays

In [22]:
arr= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)

print("shape of array", arr.shape)
print()

x= arr.reshape(2,6)
print(x)
print("shape of new array", x.shape)
print()

y= arr.reshape(1,6,2)
print(y)
print()

z= arr.reshape(3,4)
print(z)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
shape of array (12,)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
shape of new array (2, 6)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# Iterating Arrays

In [23]:
arr= np.array([1,2,3,4,5,6,7])

for i in arr:
    print(i)

1
2
3
4
5
6
7


In [24]:
arr= np.array([[1, 2, 3, 4, 5],
                [6,7,8,9,10]])

for i in arr:
    print(i)

print()

print("each scalar element:")
for i in arr:
    for j in i:
        print(j)

print()

for i in np.nditer(arr[: , 1:3:]):
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]

each scalar element:
1
2
3
4
5
6
7
8
9
10

2
3
7
8


# Joining NumPy Arrays

In [25]:
x= np.array([1,2,3,4])
y= np.array([5,6,7,8])

arr= np.concatenate((x,y))

print(arr)

[1 2 3 4 5 6 7 8]


## joining 2-D array

In [26]:
x= np.array([[1,2,3,4], [5,6,7,8]])
y= np.array([[10,11,12,13], [14,15,16,17]])

arr= np.concatenate((x,y))
print(arr)
print()

print("with axis 1 ")
arr= np.concatenate((x,y), axis= 1)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 13]
 [14 15 16 17]]

with axis 1 
[[ 1  2  3  4 10 11 12 13]
 [ 5  6  7  8 14 15 16 17]]


# Splitting NumPy Arrays

In [29]:
arr= np.array([1,2,3,4,5,6,7,8])

x= np.array_split(arr, 2)

print(x)

print()

y= np.array_split(arr, 4)
print(y)

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


## splitting 2D array

In [35]:
x= np.array([[1,2],[3,4], [5,6],[7,8], [9,10], [11,12]])

arr= np.array_split(x, 3)
print(arr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


# Searching Arrays

In [36]:
arr= np.array([1,2,3,4,5,6,7,8,9])

x= np.where(arr== 4)
print(x)

(array([3]),)


In [44]:
arr= np.array([1,2,3,4,5,6,7,8,9])

x= np.searchsorted(arr, 7)

print("number 4 index is",x)

number 4 index is 6


## 2D array search

In [49]:
arr= np.array([[1,2,3,4],[5,6,7,8]])

x= np.where(arr== 8)
print(x)

(array([1]), array([3]))


# Sorting Arrays

In [52]:
arr= np.array([4,5,23,8,2,9])
print("unsorted array")
print(arr)

print()

print("sorted array")
print(np.sort(arr))

unsorted array
[ 4  5 23  8  2  9]

sorted array
[ 2  4  5  8  9 23]


In [57]:
arr= np.array([[7,3,14,9,1], [11,2,5,6,8]])

print("unsorted array")
print(arr)

print()

print("sorted 2D array")
print(np.sort(arr))
print()

unsorted array
[[ 7  3 14  9  1]
 [11  2  5  6  8]]

sorted 2D array
[[ 1  3  7  9 14]
 [ 2  5  6  8 11]]



# Filtering Arrays

In [58]:
arr= np.array([10, 11, 12, 13])
x= [True,False, True, False]

new= arr[x]

print(new)

[10 12]


In [61]:
arr= np.array([10, 11, 12, 13, 14, 15])
x= []

for i in arr:
    if i%2==0:
        x.append(True)
    else:
        x.append(False)

print(x)
new= arr[x]
print(new)        

[True, False, True, False, True, False]
[10 12 14]


In [62]:
arr= np.array([10, 11, 12, 13, 14, 15])
x= arr > 12

new= arr[x]

print(x)
print()

print(new)

[False False False  True  True  True]

[13 14 15]


# Random Numbers in NumPy

In [1]:
import numpy as np
x = np.random.randint(100)
print(x)

79


## another way to define random

In [2]:
from numpy import random 

x= random.randint(100)
print(x)

58


### random float number

In [3]:
from numpy import random

x= random.rand()
print(x)

0.6827201230903194


## Geuss game from random

In [1]:
import numpy as np

x= np.random.randint(100)

geuss= int(input("enter a number:"))

while geuss!=x:
    if geuss>x:
        print("number is higher, enter again.")
    else:
        print("number is lower, enter again.")
    
    geuss = int(input("Enter a number: "))

print("you are right")

enter a number: 45


number is lower, enter again.


Enter a number:  60


number is lower, enter again.


Enter a number:  70


number is lower, enter again.


Enter a number:  80


number is lower, enter again.


Enter a number:  90


number is higher, enter again.


Enter a number:  85


number is lower, enter again.


Enter a number:  88


number is higher, enter again.


Enter a number:  87


you are right


## Generate Random Array

In [1]:
import numpy as np
arr= np.random.randint(100, size=5)

print(arr)

[16 52 58 30 61]


In [2]:
arr= np.array([1,2,4,6,9,11])

x= np.random.choice(arr)

print(x)

11


# Numpy Universal Functions/ufuncs

In [13]:
x= [1,2,3,4]
y= [5,6,7,8]

arr=np.add(x,y)

print(arr)

[ 6  8 10 12]


In [10]:
def myadd(x, y):
    return x+y

myadd= np.frompyfunc(myadd,2, 1)

print(myadd([1,2,3,4], [5,6,7,8]))

[6 8 10 12]


In [16]:
x= np.array([1,2,3,4])
y= np.array([5,6,7,8])

arr=np.sum([x,y])

print(arr)

36


In [17]:
x= [1,2,3,4,5,6,7,8]

arr=np.cumsum(x)

print(arr)

[ 1  3  6 10 15 21 28 36]


## Differences

In [4]:
import numpy as np

arr= np.array([10, 14, 20, 7, 45])

x= np.diff(arr)

print(x)

[  4   6 -13  38]


In [5]:
arr= np.array([10, 14, 20, 7, 45])

x= np.diff(arr, n=2)

print(x)

[  2 -19  51]


# Finding LCM in Arrays

In [6]:
x= 10
y= 25

lcm= np.lcm(x, y)

print(lcm)

50


In [7]:
arr= np.array([3, 12, 21])

lcm= np.lcm.reduce(arr)

print(lcm)

84


# Finding GCD in Arrays

In [8]:
x= 10
y= 25

gcd= np.gcd(x, y)

print(gcd)

5


In [9]:
arr= np.array([15, 12, 21])

gcd= np.gcd.reduce(arr)

print(gcd)

3
